#!/bin/bash
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias l='ls -lAG'
alias e='$EDITOR'
alias a='ag --ignore log --ignore tags'
alias g='ag'

# no-ops for when I mis-vim my windows
function k()   { :}
function kk()  { :}
function kkk() { :}
function j()   { :}
function jj()  { :}
function jjj() { :}

if [[ -z "$(which fzf)" ]]; then
  alias v='/usr/local/bin/vim'
else
  function smartvim() {
    if [[ -z "$1" ]]; then
      vim $(fzf)
    else
      vim $*
    fi
  }
  alias v='smartvim'
fi

alias grab='cat | pbcopy'
alias trail='tail -n 300 -F'
alias ack='ack --smart-case'

alias ip='ipconfig getifaddr en0'
alias httpdump="sudo tcpdump -i en0 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
alias warmup='seq 1 8 | xargs -n 1 -P 8 yes > /dev/null'
alias top='top -o cpu'

alias timestamp="date +%Y-%m-%d-%H-%M-%S"
alias jsonpretty='python -mjson.tool'
alias clj='rlwrap clj'
alias ccat='pygmentize -g'
alias cless='pygmentize -g | less -r'

[[ -f ~/.aliases.local ]] && . ~/.aliases.local

function name {
  dir=$2;
  [[ -n $dir ]] || dir=.
  find $dir -name "*$1*"
}

function dotfiles {
  cd ~/.dotfiles
  git commit -a -m "$*"
  git pull --rebase
  git push
  cd -
}

function camelcase {
  if [[ -z $1 ]]; then
    gsed 's/\(^[a-z]\)\|_\([a-z]\)/\U\1\U\2/g'
  else
    echo $* | camelcase
  fi
}
function c {
  if [[ -n $TMUX ]]; then
    tmux rename-window $(basename $1 | camelcase)
  fi
  cd $1
}

function tac {
  local line
  if IFS= read -r line
  then
    tac
    printf '%s\n' "$line"
  fi
}

function reset-ssh() {
  local operator='d'
  cmd=$(history | egrep '^\s*\d+\s+ssh' | tail -n 1 | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')

  echo "Last command: \"$cmd\""
  out=$(eval ${cmd} 2>&1)
  line=$(egrep -o 'known_hosts:\d+' <<<$out | cut -c 13-)

  echo "removing ~/.ssh/known_hosts:$line"
  sed -i.bak -e "$line$operator" ~/.ssh/known_hosts

  echo "Repeating: $cmd"
  eval $cmd
}
