#!/bin/bash
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias l='ls -lAG'
alias e='$EDITOR'
if [[ -z "$(which fzf)" ]]; then
  alias v='/usr/local/bin/vim'
else
  alias v='/usr/local/bin/vim $(fzf)'
fi
alias a='ag'
alias g='ag'

alias grab='cat | pbcopy'
alias trail='tail -n 300 -f'
alias ack='ack --smart-case'

alias ip='ipconfig getifaddr en0'
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
alias warmup='seq 1 8 | xargs -n 1 -P 8 yes > /dev/null'
alias top='top -o cpu'

alias timestamp="date +%Y%m%d%H%M%S"
alias jsonpretty='python -mjson.tool'
alias clj='rlwrap clj'
alias ccat='pygmentize -g'
alias cless='pygmentize -g | less -r'

[[ -f ~/.aliases.local ]] && . ~/.aliases.local

function name {
  dir=$2;
  [[ -n $dir ]] || dir=.
  find $dir -name "*$1*"
}

function dotfiles {
  cd ~/.dotfiles
  git commit -a -m "$*"
  git pull --rebase
  git push
  cd -
}

function camelcase {
  if [[ -z $1 ]]; then
    gsed 's/\(^[a-z]\)\|_\([a-z]\)/\U\1\U\2/g'
  else
    echo $* | camelcase
  fi
}
function c {
  if [[ -n $TMUX ]]; then
    tmux rename-window $(basename $1 | camelcase)
  fi
  cd $1
}
