#!/bin/bash

alias dps="docker ps"

# A shorthand for running a complex docker command and printing it first
docker-echo () {
  echo "=>" docker $@ 1>&2
  docker $@
}

docker-all () {
  docker ps | tail +2 | awk '{print $1 }'
}
docker-first () {
  docker-all | head -n 1 | awk '{print $1 }'
}
docker-last () {
  docker-all | tail -n 1 | awk '{print $1 }'
}

docker-exec () {
  if [[ -z $1 ]]; then
    echo "Usage: docker-exec [all|first|last|container_id] CMD"
    return
  fi
  case $1 in
    all)
      docker-all | xargs -n 1 -I {} docker-echo exec {} "${@:2}"
    ;;
    first)
      docker-echo exec $(docker-first) "${@:2}"
    ;;
    last)
      docker-echo exec $(docker-last) "${@:2}"
    ;;
    *)
      # Assume the arguments are just a CMD to be run on the last container
    docker-exec last "$@"
    ;;
  esac
}

docker-kill () {
  if [[ -z $1 ]]; then
    echo "Usage: docker-kill [all|first|last|container_id]"
    return
  fi
  case $1 in
    all)
      docker-all | while read id; do docker-echo kill $id; done
    ;;
    first)
      docker-first | while read id; do docker-echo kill $id; done
    ;;
    last)
      docker-last | while read id; do docker-echo kill $id; done
    ;;
    *)
      docker-all | grep $1 | while read id; do docker-echo kill $id; done
    ;;
  esac
}
alias dkill=docker-kill

# If in a directory with a Dockerfile build that dockerfile and immediately run
# the image that results, passing along all arguments as flags to `docker run`.
# Anything passed after the argument-final '--' will be passed as a runtime
# command for the docker container to execute
docker-build-and-run() {
  local image
  local args=('run')
  declare -a args
  local cmd

  USAGE=<<-EOUSAGE

    docker-build-and-run
    -> docker build .
    -> docker run THE_BUILT_IMAGE

    docker-build-and-run -P
    -> docker build .
    -> docker run -P THE_BUILT_IMAGE

    docker-build-and-run -P -p 2000:3000 -- sh -c "echo hello"
    -> docker build .
    -> docker run -P -p 2000:3000 THE_BUILT_IMAGE sh -c "echo hello"
EOUSAGE

  if [[ ! -f Dockerfile ]]; then
    echo $USAGE
    return 1
  fi

  echo -n "docker build ."
  build_out=$(2>&1 docker build .)
  if [[ 0 -ne $? ]]; then
    echo $build_out
    return 1
  fi

  image=$(tail -n 1 <<< $build_out | awk '{print $3}')
  echo " => $image"
  # Is a command specified?
  if grep -q -- -- <<< $@; then
    # Clear out the args array and rebuild by hand.
    for token in "$@"; do
      [[ '--' == $token ]] && token=$image
      args+=($token)
    done
  else
    # Just append the image name, nothing fancy here.
    for token in "$@"; do
      args+=($token)
    done
    args+=($image)
  fi

  docker-echo ${args[@]}
  return $?
}

