#!/bin/bash

&>/dev/null which go && path+=$(go env GOPATH)/bin

# `cd` to a specific package
function gocd {
  c `golang-package`
}

# find the directory of the first package name partially matching $1
function golang-package {
  if uname | grep Darwin -q; then
    find $(go env GOPATH)/src -depth 3 -type d | fzf
  else
    find $(go env GOPATH)/src -depth -maxdepth 3 -type d | fzf
  fi
}
