#!/bin/bash

export PYTHONSTARTUP=~/.pystartup

function apip() {
  if [[ -z $1 ]]; then
    echo "USAGE: apip term"
    return
  fi
  a "$@" $VIRTUAL_ENV/lib/python*/site-packages
}

pyenv() {
  unfunction pyenv
  if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
  fi
}

# lazy-load virtualenv functions

function virtualenv {
  unfunction virtualenv
  export VIRTUALENVWRAPPER_PYTHON=$(which python3)
  >/dev/null which virtualenvwrapper.sh && source $(which virtualenvwrapper.sh)
  virtualenv "$@"
}

function mkvirtualenv() {
  unfunction mkvirtualenv
  source $(which virtualenvwrapper.sh)
  mkvirtualenv "$@"
}

function workon() {
  unfunction workon
  export WORKON_HOME=$HOME/.virtualenvs
  export PROJECT_HOME=$HOME/.virtualenvs/devel
  source $(which virtualenvwrapper.sh)
  workon "$@"
}

