#!/bin/bash

export PAGER="less -FRSX"


if [[ -z `which seq` ]]; then
  seq() { for ((i=$1; i<= $2; i++)); do echo $i; done }
fi

function profile {
  $EDITOR ~/.profile.local && source ~/.profile.local
}

[ -f ~/.profile.local ] && . ~/.profile.local


PATH=$PATH:~/bin
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:/sq/config_files/bin
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/share/python:$PATH
export PATH=/sq/topsoil/bin:$PATH
